import Head from 'next/head'

//components
import Register from '../../../components/auth/register/Register'
import Navbar from '../../../components/landingpage/Navbar'


export default function Home() {
  return (
    <div >
    <Head>
      <title>فروشگاه ||  ثبت نام  </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  <header>
<Navbar />
  </header>
  <main>
<Register />
  </main>
  </div>
  )
}

