import React, { useContext } from 'react'
import Head from 'next/head'

//context
import { AuthContext } from '../../../store/authcontext'
import Navbar from '../../../components/landingpage/Navbar'
import Updatepassword from '../../../components/dashboard/userdash/updatepassword'


function Updatepass({params }) {
    const {authState}= useContext(AuthContext)
    if(authState.user&& authState.user?.userId == params){
        return (
          <div >
          <Head>
            <title>فروشگاه ||  ویرایش پسورد  </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        <header>
      <Navbar />
        </header>
        <main>
      <Updatepassword />
        </main>
        </div>
     )
    }else{
        return(
            <p>شما اجازه دسترسی ندارید . </p>
        )
    }
  }

export const getServerSideProps = (context)=>{
    const {params} = context.params
    return{
        props:{
          params,
        }
    }
}

export default Updatepass