import Head from 'next/head'

//components
import Login from '../../../components/auth/login/Login'
import Navbar from '../../../components/landingpage/Navbar'


export default function Home() {
  return (
    <div >
    <Head>
      <title>فروشگاه || ورود  </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  <header>
<Navbar />
  </header>
  <main>
<Login />
  </main>
  </div>
  )
}

