import Head from 'next/head'
import { useState } from 'react'
import axios from 'axios'

//components
import HeaderSlider from '../components/landingpage/hederSlider'
import Collections from '../components/main/collectons'
import Navbar from '../components/landingpage/Navbar'
import Blog from '../components/main/blog/Blog'
import Footer from '../components/footer'


export default function Home({cats , lastposts}) {
  
  const [data, setData] = useState(cats.data);
  return (
    <div >
      <Head>
        <title>فروشگاه || صفحه اصلی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <header>
<Navbar />
<HeaderSlider />
    </header>
    <main>
<Collections cats={data} setData={setData} lastposts={lastposts} />
<Blog lastposts={lastposts}/>
    </main>
    <footer>
<Footer />
    </footer>
      </div>
  )
}
export const getServerSideProps = async (context) => {
  const getcats = (
    await axios.get("/api/admin/posts/createcats", {
      params: { type: "cats", text: "کلاه" },
    })
  ).data;
  const getlastposts = (
    await axios.get("/api/admin/posts/post", {
      params: { type: "last"},
    })
  ).data;
  return {
    props: {
      cats: getcats,
      lastposts:getlastposts,
    },
  };
};

